### ISSUE TITLE
Deployment of BinderHub with Dask Gateway

### ISSUE THREAD

**Issue by sebastian-luna-valero** [pangeo-data/pangeo-eosc#25]
Hello,

Another pending tasks we have is the deployment of `binderhub` alongside `daskhub`. I am creating this issue to track progress on that front.

I found this https://github.com/pangeo-data/pangeo-binder which hasn't been updated for the last two years. Are you aware of any follow up project?

I also found https://github.com/2i2c-org/infrastructure/tree/master/helm-charts/binderhub which is a good starting point but I miss a bit of documentation for the deployment steps (or maybe I lack the expertise to proceed).

Any suggestions?

Many thanks,
Sebastian

**Comment by guillaumeeb** [comment]
I think you found every resources. Pangeo binder was community maintained in the first link, then it was taken by 2i2c, but this gets more complicated at this point.

Currently, Pangeo binderhub are stopped due to crypto mining issue. 

When I looked on 2i2c doc, I also found it really complex. I guess we need to dig a bit with those two links. We can also ask for help!

Maybe @rabernat @yuvipanda @sgibson91 @consideRatio has some hints on how to deploy a "simple" Pangeo enabled Binderhub?

**Comment by sgibson91** [comment]
2i2c deployment documentation is here https://infrastructure.2i2c.org/en/latest/ but I would treat it as guidelines rather than the de facto way to deploy since it is specialised to our engineering team managing multiple clusters/hubs from a single repo (e.g., there are specialised tools involved like our bespoke deployer module). Instead, I'd go with the steps in https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/index.html and drop in whichever chart you want to use. Also, the binderhub helm chart 2i2c maintains is i) very new, we only have one instance of it deployed which also got shut down by crypto-mining; and ii) not published anywhere, so you'll need a local checkout of that folder from the 2i2c/infrastructure repo if you really want to use it.

**Comment by guillaumeeb** [comment]
Thanks @sgibson91! I guess we'll start with Binderhub docs and see what was added in the old Pangeo Helm chart. We just need to enable users to use dask-gateway through Binder in the end.

**Comment by sgibson91** [comment]
@guillaumeeb In the pangeo-binder repo, they have a [helm chart](https://github.com/pangeo-data/pangeo-binder/tree/staging/pangeo-binder) that depends on _both_ binderhub and dask-gateway (as well as nginx-ingress for load balancing, I would update that to ingress-nginx if I were you). So those are the two pieces you need. So if you have a local checkout of that repo, whenever you see something like `helm install binderhub`, you can run `helm install pangeo-binder` instead and that will deploy binderhub and dask-gateway together. I would basically copy the config of the pangeo-binder repo - which is all we did in 2i2c and maybe added our scratch bucket stuff on top.

**Comment by guillaumeeb** [comment]
I posted the same time as you did @sgibson91, thanks a lot for this last comment!! This is very much appreciated.

**Comment by sebastian-luna-valero** [comment]
Thanks!

Getting back to basics for my own future reference. The helm chart for binderhub installs binderhub and jupyterhub. The helm chart for daskhub installs jupyterhub and dask gateway. Installing both helm charts on the same namespace is not possible (errors deploying jupyterhub twice).

The goal now is to deploy jupyterhub first, then:
* deploy binderhub and connect it to the jupyterhub previously deployed
* deploy daskhub and connect it to the jupyterhub previously deployed

Is this correct?

**Comment by sgibson91** [comment]
No, installing binderhub and daskhub again will cause the same errors because they will always try to install a JupyterHub, even when one already exists.

First off, I would suggest deleting your namespace so we can start afresh.

Then:

1. install Binderhub, and then;
2. install [dask-gateway](https://gateway.dask.org/install-kube.html#install-the-dask-gateway-helm-chart) and connect it to the JupyterHub deployed by the binderhub the chart (this is what the pangeo-binder helm chart chart in the repo linked linked above does)

**Comment by sebastian-luna-valero** [comment]
Many thanks for your help @sgibson91 

We have been testing this out. It's currently not deployed but we managed to [get it working](https://github.com/pangeo-data/pangeo-eosc/tree/main/providers/kubernetes#binderhub-and-dask-gateway).
