### ISSUE TITLE
Give access to Pangeo platforms to potential admins

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-eosc#6]
@j34ni, could you give me access to every Pangeo platforms through IM Dashboard?

This is so I can connect to it to modify configuration if needed (essentially helm or kubectl if needed).

Maybe the access should be given to others to, @tinaok ?

**Comment by j34ni** [comment]
@guillaumeeb @tinaok Sure, please send me a new OIDC auth Token tomorrow morning, the current one has expired

**Comment by guillaumeeb** [comment]
Thanks @j34ni, just done it by email.

**Comment by j34ni** [comment]
I have now 

-  deleted pangeo-xxlarge;
-  reduced the former pangeo-foss4g to the bare minimum (1 VM for the front and another for 1 node) so that you guys can recover whatever you had there (notice that the name was changed to https://pangeo-foss.vm.fedcloud.eu/jupyterhub/hub/login) - then we will delete it also
- increased the size of the new pangeo-foss4g as much as I could using the new HPC flavor, that is 1 VM for the front and 6 for the nodes (anything more makes it fail)

That leaves 64 vCPUs (+ what we could get by deleting other small ones) and we we could use them for another separate infrastructure, perhaps without EGI check-in, for those attendees who may not have completed all the registration steps?

**Comment by j34ni** [comment]
@tinaok : There is something wrong and I get this error:
**_ERROR Error in 'change_user' operation: Error modifying infrastructure owner: Invalid new infrastructure data provided: Invalid InfrastructureManager credentials. OIDC auth Token expired.._**
It has worked before for Guillaume and Anne though.
When did you regenerate this token, was it today August 19th (or is this an old one)?

@guillaumeeb @annefou: can one of you please try to add Tina as an owner?

**Comment by guillaumeeb** [comment]
I think this is done now!
