### ISSUE TITLE
updating pangeo version

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#61]
The version of pangeo docker image is 1 year old, we would like that to be updated before the BIDS23 tutorial.
How can we proceed @sebastian-luna-valero ?

**Comment by sebastian-luna-valero** [comment]
Hi Tina,

Yes, we pinned https://hub.docker.com/r/pangeo/pangeo-notebook/tags?page=1&name=2022.08.19 since this was the only version that was working with: https://github.com/pangeo-data/foss4g-2022/blob/main/tutorial/pangeo101/dask_introduction.ipynb. Updating `pangeo-notebook` to a new version will make this notebook fail.

Do you still prefer to upgrade? If so, to which version? `2023.10.28` from https://quay.io/repository/pangeo/pangeo-notebook?tab=tags for example?

Best regards,
Sebastian

**Comment by tinaok** [comment]
Hi Sebastian,

thank you for your reply. For our new tutorial that version is too old.  Let's give a try with the latest pangeo docker image.   2023.10.28 should be the right version.

Thank you!
regards, Tina

**Comment by sebastian-luna-valero** [comment]
Please reopen in case of issues.
