### ISSUE TITLE
Store Pangeo platform configurations and how to install on EOSC in this repository

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-eosc#7]
I already mentioned that in https://github.com/pangeo-data/pangeo-eosc/issues/5#issuecomment-1217817626. 

I think we should at least be storing here the helm values.yaml file. Possibly in two separated files to keep secrets elsewhere. Thereis probably a way to store secrets on github via encrypted files. I used ansible vaults previously, this is usually linked to ansible, and there is probably alternatives.

We should also add some documentation on how to install the full stack. We could start from @sebastian-luna-valero https://github.com/sebastian-luna-valero/pangeo-eosc/blob/egi/EGI.md.

**Comment by sebastian-luna-valero** [comment]
Happy to work on this on the next few days.

**Comment by guillaumeeb** [comment]
That would be really nice @sebastian-luna-valero! Thanks.

**Comment by sebastian-luna-valero** [comment]
I have worked with Ansible vault previously as well but I can't think of how to apply it here easily. I am not sure about the method to securely share/configure secrets in this context and due to the time limitation for the workshop I would just use the `Copy` functionality in Markdown document on GitHub for the time being and create a new issue to work on this for future editions of the workshop or the infrastructure.

**Comment by guillaumeeb** [comment]
That's fine by me @sebastian-luna-valero. Let's go this way for the time being.
